### ISSUE TITLE
Missing eslint v2 and v3 compatible config files

### ISSUE THREAD

**Issue by marlowpayne** [mobify/mobify-code-style#115]
Directly related to #106 , and with v3 of eslint being using by the Progressive Web SDK, we are currently lacking a v2 and v3 compatible eslint config file in the repo.

**Comment by DanielBrookRoberge** [comment]
Is this for the ES5 styles? I can put that together.

**Comment by marlowpayne** [comment]
Yes @DanielBrookRoberge . Thanks for working on this. You can start with the existing `.eslintrc` config file and bring it forward through v2 and v3. ESLint has [migration docs](http://eslint.org/docs/user-guide/migrating-to-2.0.0)

**Comment by DanielBrookRoberge** [comment]
I've got a PR up for that in #116
