### ISSUE TITLE
Maximum formal parameters limitation is exceeded with files that have many dependencies

### ISSUE THREAD

**Issue by tedtate** [mobify/mobify-code-style#20]
The following rule is causing us some trouble due to having a define statement where we are loading in a whole wack of dependencies.

```"maxparams": 10,```

This fails on the following code:
```
define([
    'resizeImages',
    'adaptivejs/selectorEngine',
    'adaptivejs/utils',
    'adaptivejs/defaults',
    'includes/header',
    'includes/footer',
    'includes/search',
    'includes/pinny-left',
    'includes/pinny-right',
    'dust!templates/base',
    'settings'
],
function(ResizeImages,
         $,
         Utils,
         Defaults,
         header,
         footer,
         search,
         pinnyLeft,
         pinnyRight,
         template,
         Settings) {
```

In my mind this is not a crazy thing to do based on the current limitations of AdaptiveJS (includes are not allowed to have their own includes). Thoughts?

**Comment by marlowpayne** [comment]
Gonna go ahead and close out this issue.
